### ISSUE TITLE
Error on Install, No File

### ISSUE THREAD

**Issue by bossoboss** [rgl/packer-provisioner-windows-update#15]
Having used on windows 2012 R2 with no issues, I am finding that on windows 2016 core I am getting an no file error when the provisioner attempts to install the updates and then fails with error. 

```
==> amazon-ebs: Running Windows update...
    amazon-ebs: #< CLIXML
    amazon-ebs: Searching for Windows updates...
    amazon-ebs: Skipped (filter) Windows update (2018-05-17; 1273.25 MB): 2018-05 Cumulative Update for Windows Server 2016 for x64-based Systems (KB4103720)
    amazon-ebs: Found Windows update (2018-05-17; 11.43 MB): 2018-05 Update for Windows Server 2016 for x64-based Systems (KB4132216)
    amazon-ebs: Found Windows update (2018-05-30; 5.78 MB): Update for Windows Defender antimalware platform - KB4052623 (Version 4.16.17656.18052)
    amazon-ebs: Downloading Windows updates...
    amazon-ebs: Installing Windows updates...
    amazon-ebs: ERROR: Exception from HRESULT: 0x80240016
    amazon-ebs: ERROR: at <ScriptBlock>, C:\Windows\Temp\packer-windows-update.ps1: line 185
    amazon-ebs: ERROR: at <ScriptBlock>, <No file>: line 1
    amazon-ebs: ERROR EXCEPTION: System.Runtime.InteropServices.COMException (0x80240016): Exception from HRESULT: 0x80240016
    amazon-ebs: ERROR EXCEPTION:    at System.Management.Automation.ComInterop.ComRuntimeHelpers.CheckThrowException(Int32 hresult, ExcepInfo& excepInfo, ComMethodDesc method, Object[] args, UInt32 argErr)
    amazon-ebs: ERROR EXCEPTION:    at CallSite.Target(Closure , CallSite , ComObject )
    amazon-ebs: ERROR EXCEPTION:    at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
    amazon-ebs: ERROR EXCEPTION:    at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
    amazon-ebs: ERROR EXCEPTION:    at System.Management.Automation.Interpreter.DynamicInstruction`2.Run(InterpretedFrame frame)
    amazon-ebs: ERROR EXCEPTION:    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
    amazon-ebs: <Objs Version="1.1.0.1" xmlns="http://schemas.microsoft.com/powershell/2004/04"><Obj S="progress" RefId="0"><TN RefId="0"><T>System.Management.Automation.PSCustomObject</T><T>System.Object</T></TN><MS><I64 N="SourceId">1</I64><PR N="Record"><AV>Preparing modules for first use.</AV><AI>0</AI><Nil /><PI>-1</PI><PC>-1</PC><T>Completed</T><SR>-1</SR><SD> </SD></PR></MS></Obj><Obj S="progress" RefId="1"><TNRef RefId="0" /><MS><I64 N="SourceId">2</I64><PR N="Record"><AV>Preparing modules for first use.</AV><AI>0</AI><Nil /><PI>-1</PI><PC>-1</PC><T>Completed</T><SR>-1</SR><SD> </SD></PR></MS></Obj></Objs>
==> amazon-ebs: Terminating the source AWS instance...
==> amazon-ebs: Cleaning up any extra volumes...
==> amazon-ebs: No volumes to clean up, skipping
==> amazon-ebs: Deleting temporary security group...
==> amazon-ebs: Deleting temporary keypair...
Build 'amazon-ebs' errored: Windows update script exited with non-zero exit status: 1

==> Some builds didn't complete successfully and had errors:
--> amazon-ebs: Windows update script exited with non-zero exit status: 1

```

**Comment by rgl** [comment]
I'm sorry, but I have no idea why that happens. I never encountered that before (please note that I only test this with the vagrant / virtualbox provider), so YMMV.

But, the error is not really about "No File", the error is at [line 185](https://github.com/rgl/packer-provisioner-windows-update/blob/master/update/windows-update.ps1#L185) while installing a update, which raises an unexpected error:

```
amazon-ebs: ERROR: Exception from HRESULT: 0x80240016
amazon-ebs: ERROR: at <ScriptBlock>, C:\Windows\Temp\packer-windows-update.ps1: line 185
```

Maybe this happens because you are not installing the cumulative updates? You see the line `Skipped (filter) Windows update (2018-05-17; 1273.25 MB): 2018-05 Cumulative Update for Windows Server 2016 for x64-based Systems (KB4103720)`?

So, try running the provider with the suggested filters that are on the README and see if that helps. For reference, these are the suggested filters:

## Filters

You can select which Windows Updates are installed by defining a set of filters, e.g.:

```json
{
    "provisioners": [
        {
            "type": "windows-update",
            "filters": [
                "exclude:$_.Title -like '*Preview*'",
                "include:$_.Title -like '*Cumulative Update for Windows*'",
                "include:$_.AutoSelectOnWebSites"
            ]
        }
    ]
}
```

**NB** If the `filters` attribute is not declared, only important updates are installed (equivalent of declaring a single `include:$_.AutoSelectOnWebSites` filter).

**Comment by tvories** [comment]
I'm getting a 0x80240016 on Windows Server 2016 as well.  I'm using the same filter as @rgl.  This only started happening recently.

**Comment by tvories** [comment]
I was able to get beyond this error by running the windows_restart provisioner before running windows_update.  That error appears to be some sort of pending reboot error.

**Comment by rgl** [comment]
This update script is checking for pending reboots before doing anything, so it seems there's something missing in the [ExitWhenRebootRequired function](https://github.com/rgl/packer-provisioner-windows-update/blob/master/update/windows-update.ps1#L93-L113) which detects pending reboots. Do you have any idea what is missing?

**Comment by tvories** [comment]
I'll have to do some debug on a 2016 build.  I'm running into some weird 2008 R2 bugs right now, too, but I'll make a new issue if it's not a config issue.

**Comment by rgl** [comment]
Please try with the new 0.6.0 and packer 1.2.5 (restart is broken after that release, so stick with 1.2.5 for now), winrm, and use the provision step without any options, i.e.:

```json
{
    "provisioners": [
        {
            "type": "windows-update"
        }
    ]
}
```

It should now install all recommended updates alike the windows update ui.

Please note that I've only tried this with Windows 2012 R2 and 2016.

**Comment by gstorme** [comment]
I also have this, on both packer 1.2.5 with update provisioner 0.5.1 and 0.6.0, and packer 1.3.2 with update provisioner 0.6.0, on a Windows 2016 build.  

```
==> vsphere-iso: Machine successfully restarted, moving on
==> vsphere-iso: Pausing 5m0s before the next provisioner...
==> vsphere-iso: Uploading the Windows update elevated script...
==> vsphere-iso: Uploading the Windows update script...
==> vsphere-iso: Running Windows update...
    vsphere-iso: #< CLIXML
    vsphere-iso: Searching for Windows updates...
    vsphere-iso: Found Windows update (2018-05-17; 1273,25 MB): 2018-05 Cumulative Update for Windows Server 2016 for x64-based Systems (KB4103720)
    vsphere-iso: Found Windows update (2018-05-17; 11,43 MB): 2018-05 Update for Windows Server 2016 for x64-based Systems (KB4132216)
    vsphere-iso: Found Windows update (2018-10-09; 45,85 MB): Windows Malicious Software Removal Tool x64 - October 2018 (KB890830)
    vsphere-iso: Found Windows update (2018-11-05; 164,72 MB): Definition Update for Windows Defender Antivirus - KB2267602 (Definition 1.279.1221.0)
    vsphere-iso: Downloading Windows updates...
    vsphere-iso: Installing Windows updates...
    vsphere-iso: ERROR: Exception from HRESULT: 0x80240016
    vsphere-iso: ERROR: at <ScriptBlock>, C:\Windows\Temp\packer-windows-update.ps1: line 185
    vsphere-iso: ERROR: at <ScriptBlock>, <No file>: line 1
    vsphere-iso: ERROR EXCEPTION: System.Runtime.InteropServices.COMException (0x80240016): Exception from HRESULT: 0x80240016
    vsphere-iso: ERROR EXCEPTION:    at System.Management.Automation.ComInterop.ComRuntimeHelpers.CheckThrowException(Int32 hresult, ExcepInfo& excepInfo, ComMethodDesc method, Object[] args, UInt32 argErr)
    vsphere-iso: ERROR EXCEPTION:    at CallSite.Target(Closure , CallSite , ComObject )
    vsphere-iso: ERROR EXCEPTION:    at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
    vsphere-iso: ERROR EXCEPTION:    at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
    vsphere-iso: ERROR EXCEPTION:    at System.Management.Automation.Interpreter.DynamicInstruction`2.Run(InterpretedFrame frame)
    vsphere-iso: ERROR EXCEPTION:    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
    vsphere-iso: <Objs Version="1.1.0.1" xmlns="http://schemas.microsoft.com/powershell/2004/04"><Obj S="progress" RefId="0"><TN RefId="0"><T>System.Management.Automation.PSCustomObject</T><T>System.Object</T></TN><MS><I64 N="SourceId">1</I64><PR N="Record"><AV>Preparing modules for first use.</AV><AI>0</AI><Nil /><PI>-1</PI><PC>-1</PC><T>Completed</T><SR>-1</SR><SD> </SD></PR></MS></Obj><Obj S="progress" RefId="1"><TNRef RefId="0" /><MS><I64 N="SourceId">2</I64><PR N="Record"><AV>Preparing modules for first use.</AV><AI>0</AI><Nil /><PI>-1</PI><PC>-1</PC><T>Completed</T><SR>-1</SR><SD> </SD></PR></MS></Obj></Objs>
==> vsphere-iso: Power off VM...
==> vsphere-iso: Destroying VM...
Build 'vsphere-iso' errored: Windows update script exited with non-zero exit status: 1
```

Packer file:  

```
{
  "provisioners": [
    {
      "type": "windows-shell",
      "scripts":[
        "./windows/scripts/2016/disable-fw.bat",
        "./windows/scripts/2016/enable_rdp.bat",
        "./windows/scripts/2016/enable_credssp.bat"
      ]
    },
    {
      "type": "windows-restart",
      "pause_before": "1m"
    },
    {
      "type": "windows-update",
      "filters": [
        "exclude:$_.Title -like '*Preview*'",
        "include:$_.Title -like '*Cumulative Update for Windows*'",
        "include:$_.AutoSelectOnWebSites"
      ],
      "pause_before": "5m"
    },
    {
      "type": "windows-restart",
      "pause_before": "1m"
    }
  ],
```

**Comment by ramkrt** [comment]
I am using latest packer and the provisioner. I am using azurerm builder. All runs are failing with the same error with or without the filters,

    win-arm: Searching for Windows updates...
    win-arm: Found Windows update (2018-10-18; 1350.96 MB): 2018-10 Cumulative Update for Windows Server 2016 for x64-based Systems (KB4462928)
    win-arm: Found Windows update (2018-10-22; 5.64 MB): Update for Windows Defender Antivirus antimalware platform - KB4052623 (Version 4.18.1810.5)
    win-arm: Found Windows update (2018-11-09; 82.39 MB): Definition Update for Windows Defender Antivirus - KB2267602 (Definition 1.279.1515.0)
    win-arm: Downloading Windows updates (2 updates; 1356.59 MB)...
    win-arm: Installing Windows updates...
    win-arm: ERROR: Exception from HRESULT: 0x80240016
    win-arm: ERROR: at <ScriptBlock>, C:\Windows\Temp\packer-windows-update.ps1: line 220
    win-arm: ERROR: at <ScriptBlock>, <No file>: line 1
    win-arm: ERROR EXCEPTION: System.Runtime.InteropServices.COMException (0x80240016): Exception from HRESULT: 0x80240016
    win-arm: ERROR EXCEPTION:    at System.Management.Automation.ComInterop.ComRuntimeHelpers.CheckThrowException(Int32 hresult, ExcepInfo& excepInfo, ComMethodDesc method, Object[] args, UInt32 argErr)
    win-arm: ERROR EXCEPTION:    at CallSite.Target(Closure , CallSite , ComObject )
    win-arm: ERROR EXCEPTION:    at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
    win-arm: ERROR EXCEPTION:    at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
    win-arm: ERROR EXCEPTION:    at System.Management.Automation.Interpreter.DynamicInstruction`2.Run(InterpretedFrame frame)

**Comment by ramkrt** [comment]
I have had successful runs with / without filters since my last post. Wish to have this error handled better as it looks like intermittent issue.

**Comment by bsteeleverint** [comment]
I can get this error consistently as shown below.  Version 0.6.1 and Packer 1.3.3.  When I add the filter to not install the VMWare package, this will succeed.

```
==> vsphere-clone: Running Windows update...
2019/01/22 15:40:38 packer-builder-vsphere-clone: <Objs Version="1.1.0.1" xmlns="http://schemas.microsoft.com/powershell/2004/04"><Obj S="progress" RefId="0"><TN RefId="0"><T>System.Management.Automation.PSCustomObject</T><T>System.Object</T></TN><MS><I64 N="SourceId">1</I64><PR N="Record"><AV>Preparing modules for first use.</AV><AI>0</AI><Nil /><PI>-1</PI><PC>-1</PC><T>Completed</T><SR>-1</SR><SD> </SD></PR></MS></Obj></Objs>2019/01/22 15:40:38 [INFO] starting remote command: PowerShell -ExecutionPolicy Bypass -OutputFormat Text -File C:/Windows/Temp/packer-windows-update-elevated.ps1
    vsphere-clone: Searching for Windows updates...
    vsphere-clone: Found Windows update (2018-05-17; 1273.25 MB): 2018-05 Cumulative Update for Windows Server 2016 for x64-based Systems (KB4103720)
    vsphere-clone: Found Windows update (2018-05-17; 11.43 MB): 2018-05 Update for Windows Server 2016 for x64-based Systems (KB4132216)
    vsphere-clone: Found Windows update (2019-01-02; 0.05 MB): VMware, Inc. - SCSIAdapter - 4/6/2018 12:00:00 AM - 1.3.10.0
    vsphere-clone: Found Windows update (2019-01-08; 43.84 MB): Windows Malicious Software Removal Tool x64 - January 2019 (KB890830)
    vsphere-clone: Downloading Windows updates (4 updates; 1328.57 MB)...
    vsphere-clone: Installing Windows updates...
2019/01/22 15:48:55 packer-builder-vsphere-clone: 2019/01/22 15:48:55 [INFO] command 'PowerShell -ExecutionPolicy Bypass -OutputFormat Text -File C:/Windows/Temp/packer-windows-update-elevated.ps1' exited with code: 1
2019/01/22 15:48:55 packer-builder-vsphere-clone: 2019/01/22 15:48:55 [INFO] RPC endpoint: Communicator ended with: 1
    vsphere-clone: ERROR: Exception from HRESULT: 0x80248007
2019/01/22 15:48:55 [INFO] 0 bytes written for 'stderr'
2019/01/22 15:48:55 [INFO] 1585 bytes written for 'stdout'
2019/01/22 15:48:55 [INFO] RPC client: Communicator ended with: 1
2019/01/22 15:48:55 [INFO] RPC endpoint: Communicator ended with: 1
2019/01/22 15:48:55 packer-provisioner-windows-update: 2019/01/22 15:48:55 [INFO] 1585 bytes written for 'stdout'
2019/01/22 15:48:55 packer-provisioner-windows-update: 2019/01/22 15:48:55 [INFO] 0 bytes written for 'stderr'
2019/01/22 15:48:55 packer-provisioner-windows-update: 2019/01/22 15:48:55 [INFO] RPC client: Communicator ended with: 1
    vsphere-clone: ERROR: at <ScriptBlock>, C:\Windows\Temp\packer-windows-update.ps1: line 227
    vsphere-clone: ERROR: at <ScriptBlock>, <No file>: line 1
    vsphere-clone: ERROR EXCEPTION: System.Runtime.InteropServices.COMException (0x80248007): Exception from HRESULT: 0x80248007
    vsphere-clone: ERROR EXCEPTION:    at System.Management.Automation.ComInterop.ComRuntimeHelpers.CheckThrowException(Int32 hresult, ExcepInfo& excepInfo, ComMethodDesc method, Object[] args, UInt32 argErr)
    vsphere-clone: ERROR EXCEPTION:    at CallSite.Target(Closure , CallSite , ComObject )
    vsphere-clone: ERROR EXCEPTION:    at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
    vsphere-clone: ERROR EXCEPTION:    at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
    vsphere-clone: ERROR EXCEPTION:    at System.Management.Automation.Interpreter.DynamicInstruction`2.Run(InterpretedFrame frame)
    vsphere-clone: ERROR EXCEPTION:    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)

```

**Comment by bsteeleverint** [comment]
When I create a filter to only install the VMWare and skip the other updates, it does succeed there so something with the combination of updates.

**Comment by tvories** [comment]
I am having the same issue @bsteeleverint.  I am going to try without the vmware update and see if that fixes the problem.

**Comment by agowa338** [comment]
The errorcode 0x80240016 is the FACILITY_WINDOWSUPDATE caused WU_E_INSTALL_NOT_ALLOWED and according to [hresult.info](https://www.hresult.info/FACILITY_WINDOWSUPDATE/0x80240016) it means either mandatory reboot required or tried to install an update while something else is already installing.
So maybe we should just catch that exception do a reboot and retry?

**Comment by rgl** [comment]
Please lets follow this in #76 as it seems to fix this.
