### ISSUE TITLE
windows-2012: ERROR: Element not found. (Exception from HRESULT: 0x80070490)

### ISSUE THREAD

**Issue by jagrahamjr** [rgl/packer-provisioner-windows-update#73]
When I am running the windows update, I am receiving this error message. It is only occurring on Windows 2012 (Not R2).

During the Windows 2012 install (autounattended.xml) it updates Powershell to 5.1 and installs a single KB so the Windows updates can run via packer. (KB2996851)

I have tried with and without the Powershell and KB updates.

JSON file:
{
  "variables": {
    "windows_2012_template": "SI-WS8-Base",
    "update_criteria":    "BrowseOnly=0 and IsInstalled=0"
  },
  "sensitive-variables": ["winrm_password", "password"],
  "builders": [
    {
      "name":                   "windows-2012",
      "type":                   "vsphere-clone",
      "vcenter_server":         "{{ user `vsphere_server` }}",
      "host":                   "{{ user `vsphere_host` }}",
      "cluster":                "{{ user `vsphere_cluster` }}",
      "datacenter":             "{{ user `vsphere_datacenter` }}",
      "folder":                 "{{ user `vsphere_folder` }}",
      "resource_pool":          "{{ user `vsphere_resource_pool` }}",
      "datastore":              "{{ user `vsphere_datastore` }}",
      "username":               "{{ user `username` }}",
      "password":               "{{ user `password` }}",
      "insecure_connection":    "{{ user `insecure_connection` }}",
      "template":               "{{ user `windows_2012_template` }}",
      "vm_name":                "{{ user `windows_2012_template` }}-Updated-{{ isotime \"20060102\" }}",

      "communicator":           "winrm",
      "winrm_username":         "{{ user `winrm_username` }}",
      "winrm_password":         "{{ user `winrm_password` }}",
      "winrm_port":             "5986",
      "winrm_use_ssl":          "true",
      "winrm_insecure":         "true"
    }
  ],
  "provisioners": [
    {
      "type": "windows-update",
      "filters": [
          "include:$_.Title -like '*Servicing Stack Update for Windows*'"
      ],
      "max_retries": 2,
      "timeout": "20m",
      "pause_before": "10m"
    },
    {
      "type": "windows-update",
      "search_criteria": "{{ user `update_criteria` }}",
      "filters": [
        "exclude:$_.Title -like '*Preview*'",
        "include:$true"
      ],
      "max_retries": 5,
      "timeout": "20m",
      "pause_before": "10m",
      "update_limit": 25
    },
     {
      "type": "powershell",
      "script": "{{ template_dir }}\\setup\\autounattend\\common-scripts\\Remove-PackerSetup.ps1",
      "pause_before": "10m"
    }
  ]
}

ERROR:
2020-07-28T16:28:29-07:00: ==> windows-2012: Cloning VM...
2020-07-28T16:31:46-07:00: ==> windows-2012: Power on VM...
2020-07-28T16:32:11-07:00: ==> windows-2012: Waiting for IP...
2020-07-28T16:33:31-07:00: ==> windows-2012: IP address: 10.157.62.40
2020-07-28T16:33:31-07:00: ==> windows-2012: Using winrm communicator to connect: 192.168.1.100
2020-07-28T16:33:31-07:00: ==> windows-2012: Waiting for WinRM to become available...
2020-07-28T16:33:53-07:00: ==> windows-2012: #< CLIXML
2020-07-28T16:33:54-07:00:     windows-2012: WinRM connected.
2020-07-28T16:33:54-07:00: ==> windows-2012: <Objs Version="1.1.0.1" xmlns="http://schemas.microsoft.com/powershell/2004/04"><Obj S="progress" RefId="0"><TN RefId="0"><T>System.Management.Automation.PSCustomObject</T><T>System.Object</T></TN><MS><I64 N="SourceId">1</I64><PR N="Record"><AV>Preparing modules for first use.</AV><AI>0</AI><Nil /><PI>-1</PI><PC>-1</PC><T>Completed</T><SR>-1</SR><SD> </SD></PR></MS></Obj><Obj S="progress" RefId="1"><TNRef RefId="0" /><MS><I64 N="SourceId">1</I64><PR N="Record"><AV>Preparing modules for first use.</AV><AI>0</AI><Nil /><PI>-1</PI><PC>-1</PC><T>Completed</T><SR>-1</SR><SD> </SD></PR></MS></Obj></Objs>
2020-07-28T16:33:54-07:00: ==> windows-2012: Connected to WinRM!
2020-07-28T16:33:54-07:00: ==> windows-2012: Pausing 10m0s before the next provisioner...
2020-07-28T16:43:54-07:00: ==> windows-2012: Uploading the Windows update elevated script...
2020-07-28T16:43:55-07:00: ==> windows-2012: Uploading the Windows update check for reboot required elevated script...
2020-07-28T16:43:56-07:00: ==> windows-2012: Uploading the Windows update script...
2020-07-28T16:43:57-07:00: ==> windows-2012: Running Windows update...
2020-07-28T16:43:57-07:00:     windows-2012: ERROR: Element not found. (Exception from HRESULT: 0x80070490)
2020-07-28T16:43:57-07:00:     windows-2012: ERROR: at <ScriptBlock>, C:\Windows\Temp\packer-windows-update-elevated.ps1: line 60
2020-07-28T16:43:57-07:00:     windows-2012: ERROR EXCEPTION: System.Runtime.InteropServices.COMException (0x80070490): Element not found. (Exception from HRESULT: 0x80070490)
2020-07-28T16:43:57-07:00:     windows-2012: ERROR EXCEPTION:    at System.Management.Automation.ComInterop.ComRuntimeHelpers.CheckThrowException(Int32 hresult, ExcepInfo& excepInfo, ComMethodDesc method, Object[] args, UInt32 argErr)
2020-07-28T16:43:57-07:00:     windows-2012: ERROR EXCEPTION:    at CallSite.Target(Closure , CallSite , ComObject , Object )
2020-07-28T16:43:57-07:00:     windows-2012: ERROR EXCEPTION:    at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
2020-07-28T16:43:57-07:00:     windows-2012: ERROR EXCEPTION:    at CallSite.Target(Closure , CallSite , Object , Object )
2020-07-28T16:43:57-07:00:     windows-2012: ERROR EXCEPTION:    at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
2020-07-28T16:43:58-07:00:     windows-2012: ERROR EXCEPTION:    at System.Management.Automation.Interpreter.DynamicInstruction`3.Run(InterpretedFrame frame)
2020-07-28T16:43:58-07:00:     windows-2012: ERROR EXCEPTION:    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
2020-07-28T16:43:58-07:00: ==> windows-2012: Provisioner failed with "Windows update script exited with non-zero exit status: 1", retrying with 2 trie(s) left

**Comment by rgl** [comment]
I'm sorry, but Windows 2012 is way to old for me to look into.
