### ISSUE TITLE
Issue with Packer 1.6.5

### ISSUE THREAD

**Issue by aaronparker** [rgl/packer-provisioner-windows-update#83]
I can see the plug-in hasn't technically been updated to support Packer `1.6.5` and rolling back to `1.6.1` resolves the issue below, but I thought it worth sharing the following logs when running a Windows 10 build against the latest Packer release.

My `Packer.json` includes the below config - the issue might be caused by the multiple `exclude` line items, as my builds have been running against Packer `1.6.5` OK previously (I haven't yet confirmed this):

```json
        {
            "type": "windows-update",
            "search_criteria": "IsInstalled=0",
            "filters": [
                "exclude:$_.Title -like '*Silverlight*'",
                "exclude:$_.Title -like '*Preview*'",
                "include:$true"
            ],
            "update_limit": 25
        }
```

Which ends up producing the following issue::

```
azure-arm: ERROR: Could not find file 'C:\windows\TEMP\ub4p44di\ub4p44di.dll'.
azure-arm: ERROR: at <ScriptBlock>, C:\Windows\Temp\packer-windows-update.ps1: line 66
azure-arm: ERROR: at <ScriptBlock>, <No file>: line 1
azure-arm: ERROR EXCEPTION: System.IO.FileNotFoundException: Could not find file 'C:\windows\TEMP\ub4p44di\ub4p44di.dll'.
azure-arm: ERROR EXCEPTION: File name: 'C:\windows\TEMP\ub4p44di\ub4p44di.dll'
azure-arm: ERROR EXCEPTION:    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
azure-arm: ERROR EXCEPTION:    at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
azure-arm: ERROR EXCEPTION:    at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
azure-arm: ERROR EXCEPTION:    at System.IO.File.InternalReadAllBytes(String path, Boolean checkHost)
azure-arm: ERROR EXCEPTION:    at Microsoft.CSharp.CSharpCodeGenerator.FromFileBatch(CompilerParameters options, String[] fileNames)
azure-arm: ERROR EXCEPTION:    at Microsoft.CSharp.CSharpCodeGenerator.FromSourceBatch(CompilerParameters options, String[] sources)
azure-arm: ERROR EXCEPTION:    at Microsoft.CSharp.CSharpCodeGenerator.System.CodeDom.Compiler.ICodeCompiler.CompileAssemblyFromSourceBatch(CompilerParameters options, String[] sources)
azure-arm: ERROR EXCEPTION:    at Microsoft.PowerShell.Commands.AddTypeCommand.CompileAssemblyFromSource(List`1 generatedTypes)
azure-arm: ERROR EXCEPTION:    at Microsoft.PowerShell.Commands.AddTypeCommand.EndProcessing()
azure-arm: ERROR EXCEPTION:    at System.Management.Automation.CommandProcessorBase.Complete()
```

**Comment by rgl** [comment]
That's a really odd error and does not make sense to me (because there's nothing in this codebase that is directly creating dll files).

In the mean time there's a new packer 1.7.0 and plugin 0.11.0 version; maybe try them?

**Comment by aaronparker** [comment]
Thanks.

Since then, `1.6.5` has been behaving OK. Perhap it was an issue with the Windows image. I'll give the updated versions a spin ASAP.

**Comment by aaronparker** [comment]
Packer `1.7.0` and plug-in version `0.11.0` tested OK.

**Comment by rgl** [comment]
Nice! Thanks for testing it!

**Comment by aaronparker** [comment]
I should add that I have tested Windows 10 Enterprise 20H2, Windows 10 Enterprise multi-session 20H2 and Windows Server 2019 on Azure.
